project:
  type: website
  resources:
    - assets/
  render:     
    - index.qmd
    - about.qmd
    - appendix.qmd
    - data.qmd
    - ai-log.qmd

website:
  title: "The Billion Dollar Teenagers"
  navbar:
    left:
      - href: index.qmd
        text: The Story
      - href: about.qmd
        text: About Me
      - href: appendix.qmd
        text: Technical Appendix
      - href: ai-log.qmd
        text: AI Usage log


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    embed-resources: false
    code-fold: true



